sources:
  - id: lora_alliance
    name: LoRa Alliance
    domain: standard
    source_type: official
    method: requests
    enabled: true
    start_urls:
      - https://lora-alliance.org/
    include_keywords:
      - water meter
      - metering
      - measurement
      - communication protocol
      - NB-IoT
      - LoRaWAN
      - M-Bus
    exclude_keywords:
      - food
      - medical
      - building material

  - id: oiml_publications
    name: OIML Publications
    domain: standard
    source_type: official
    method: requests
    enabled: true
    start_urls:
      - https://www.oiml.org/en/files/

  - id: welmec
    name: WELMEC
    domain: standard
    source_type: official
    method: requests
    enabled: true
    start_urls:
      -https://www.welmec.org/
